# Generated by Django 5.1.5 on 2025-02-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_reunion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvreunion',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pv_reunion.branch'),
        ),
    ]
