# Generated by Django 5.1.5 on 2025-02-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_reunion', '0002_pvreunion_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_images/'),
        ),
    ]
