# Generated by Django 5.1.5 on 2025-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_reunion', '0003_branch_description_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cellule_images/'),
        ),
    ]
