# Generated by Django 5.1.5 on 2025-02-20 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pv_reunion', '0003_branch_description_branch_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField(default='No description provided')),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pv_reunion.branch')),
                ('cellule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pv_reunion.cellule')),
            ],
        ),
    ]
